### ISSUE TITLE
KeyError in dbtoyaml if postgis_topology extension is installed

### ISSUE THREAD

**Issue by icholy** [perseas/Pyrseas#91]
I'm trying to use `dbtoyaml` on a postgis table: 

``` sh
$ dbtoyaml -H localhost -U postgres -W -n public -t points gis_data
Password:
```

I get the following error:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/dbtoyaml", line 9, in <module>
    load_entry_point('Pyrseas==0.7.1', 'console_scripts', 'dbtoyaml')()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbtoyaml.py", line 49, in main
    dbmap = db.to_map()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 263, in to_map
    self.from_catalog()
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 173, in from_catalog
    self._link_refs(self.db)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/database.py", line 138, in _link_refs
    db.types.link_refs(db.columns, db.constraints, db.functions)
  File "/usr/local/lib/python2.7/dist-packages/pyrseas/dbobject/dbtype.py", line 364, in link_refs
    assert self[(sch, typ)]
KeyError: (u'topology', u'topoelementarray')
```

The table has 2 columns: `geometry` and `real`.

**Comment by richardolsson** [comment]
Was this solved? I'm researching schema versioning strategies for a project which relies heavily on PostGIS and find pyrseas very interesting. Do you need help solving this issue?

**Comment by jmafc** [comment]
Richard, I haven't checked on this recently, but it seems it's still pending. @dvarrazzo has been doing work on implementing a topological sort of the database objects so that we could deal with all inter-object dependencies. IIRC last time we spoke he was done with the general refactoring but had to go through each of the unit tests and/or create additional ones. We surely welcome any help.

**Comment by richardolsson** [comment]
Thanks for letting me know. I've implemented similar topological dependency graph sorting before so I could probably help, but if @dvarrazzo has already gotten as far as it sounds my involvement might prove more counter-productive than productive for this particular feature at this particular time. I look forward to being able to help on some other issue as I start using Pyrseas, though. And do let me know if you need help after all, @dvarrazzo.

**Comment by dvarrazzo** [comment]
Hi @richardolsson @jmafc 

sorry if I haven't given any more info. Unfortunately I haven't found any time to work on the topo-sort branch in the last months, and my current situation is not different.

If someone wants to pick up from where I've left I can give him a hand. Unfortunately I don't have time to work on the project now.

The state I've left the project is: I had a big database and I made sure I could dump and reload its schema only using the dependencies info. I cannot provide that schema for testing as it's sensible data but that part was working: feature-wise I think the branch is ok.

My further steps would have been:

- make the test suite run again: I've refactored mercilessly the code so it's likely the test suite doesn't run either for some changed interface or because genuine bugs introduced by my edits;
- get rid of the "optional attributes" and give Pyrseas object a more robust internal data model. This is arguably not related to the deptrack branch but we agreed it would be an improvement to the code base.

I've checked the status and my `deptrack` branch (https://github.com/dvarrazzo/Pyrseas/commits/deptrack) is in line with my laptop; I have some edits in my working copy (http://pastebin.com/YYmYCppD) which appear to be only related to the second point (it's about getting rid of stuff like `owner = self.owner if hasattr(self, 'owner') else ''` and make sure the attributes are always there instead).

Hope this helps, sorry for not being more helpful but I can definitely exchange some mail in case someone wants to pick up from where I've left.

**Comment by jmafc** [comment]
Daniele, I'm going to spend some time each day during the next few weeks going over the test suite on my clone of your `deptrack` branch. I'll report later, hopefully by end of month.

**Comment by jmafc** [comment]
Reconfirmed that this still happens in the current `0.8.dev0` version of `master` against PG 9.4 and PostGIS 2.4.1. The error now occurs in https://github.com/perseas/Pyrseas/blob/2d0a9ad57af80883206bc72264af6c0cd91f23b5/pyrseas/dbobject/trigger.py#L210 which is another variation of the original code: trying to find a function in the `db.functions` dictionary. The current error is `KeyError: ('topology', 'layertrigger', '')`.

It looks like the following `TODO` in `pyrseas/dbobject/dbtype.py` (added by @dvarrazzo) may be relevant to fixing this issue:
```
     # TODO: consider to fetch all the objects belonging to extensions:
     # not to dump them but to trace dependency from objects to the extension
```
The problem with this is that there over 1200 new functions in PostGIS and some 50-60 new types, plus if we fetch functions, types and other objects belonging to extensions we'll probably need to also fetch other PG objects (see issue #175 for an example), IOW fetch *everything* from the PG catalogs. I'm wondering if all that overhead will really be necessary.

**Comment by jmafc** [comment]
The `KeyError` error can be avoided if we comment out or remove the following lines:
https://github.com/perseas/Pyrseas/blob/2d0a9ad57af80883206bc72264af6c0cd91f23b5/pyrseas/dbobject/function.py#L142-L144
However, this results in a YAML output file with 1100 functions, none of which were created by the user. They result from the statement `CREATE EXTENSION postgis_topology` which also creates a `topology` schema. Even worse, if you `DROP EXTENSION postgis_topology` the command is accepted, but most of the functions (1021) and the schema remain!  It seems that this is a bug in either the implementation of the extension or PG extensions in general, but I don't know enough PostGIS to be sure of what is going on. If anyone is still listening to this and has experience with PostGIS, your input will be appreciated.

In any case, if I issue the following statements in a newly created database:
```sql
CREATE EXTENSION postgis;
CREATE TABLE points (
    geom geometry,
    value real
);
```
I'm able to run `dbtoyaml` and there are *no* errors. So the problem is definitely introduced by creating the `postgis_topology` extension.

**Comment by jmafc** [comment]
I have again confirmed that this problem still exists in the current master. As mentioned previously, the problem happens after you do a `CREATE EXTENSION postgis_topology`. Some additional investigation shows that when you connect to a database after issuing that command (even you're already connected), your search_path gets modified to `"$user", public, topology`. This is because the postgis_topology installation code does a `ALTER DATABASE current_database SET search_path = var_cur_search_path` via a function called `AddToSearchPath` which is called (obviously) with 'topology' as a parameter.
If we change the current Pyrseas connection code from "set search_path to pg_catalog" to add "topology" to the list, the error does not occur, and `dbtoyaml` of course shows the `topology` schema tables (two).
Since we don't want to add PostGIS-specific code to Pyrseas (and we may have a similar problem with postgraphql--see #180), a solution may be to query `SELECT current_schemas(false)` and then examining the returned array, adding any schemas--other than `public`-- to the end of the "set search_path" in the connection code.
